### PR TITLE
WIP get SPI echo test code working

### PR DESCRIPTION
**Pull request by ekfriis**
Hi @dabelknap

I'm just collecting all the fixes I do to the SPI echo tests in this PR before merging, as there are some common issues you should be aware of.   Most of this is copying over bugs we killed on the CTP6 standalone code from the August integration test that I never ported to the other program.s

Infos practiques:

If suddenly the programs won't fit in the bram, you can set GCC to optimize for size instead of speed, see (da656b7).  

Note that when setting up the interrupts, you have to also enable the Xilinx exception table (0b4e89e).  I don't know why this is necessary, but it is.

### CODE REVIEW

**Comment by ekfriis** [comment]
You need to lookup the correct device from the xparameters.h file in the corresponding BSP (497327d)

**Comment by dabelknap** [comment]
Some address strangeness in FE SPI echo test:

```
XMD% stp
    653C:   B0000000  imm      0
    6540:   30E03970  addik    r7 , r0 , 14704

XMD% stp
    6544:   B0000000  imm      0
    6548:   31007164  addik    r8 , r0 , 29028

XMD% stp
    654C:   B000FFFF  imm      -1
    6550:   B9F4A320  brlid    r15, -23776
    6554:   10D30000  addk     r6 , r19, r0

XMD% stp
     870:   DEADBEEF
```

`870` is supposed to read `870: 3021ffe0  addik  r1, r1, -32` in `<XIntc_Connect>`.

**Comment by ekfriis** [comment]
How do you know it's supposed to be that?  From the .S?

**Comment by dabelknap** [comment]
For posterity: yes, it is from payload.S

**Pull request merged**
