### PR TITLE
vme2fd with bi-directional registers

### PR DESCRIPTION
**Pull request by dabelknap**
These are the modifications to vme2fd so that it uses bi-directional registers in VME rather than uni-directional.

### CODE REVIEW

**Comment by dabelknap** [comment]
The VME PC / oRSC BE echo test works, aside from the occasional glitch I mentioned during the meeting.

**Comment by dabelknap** [comment]
@tsarangi 
These are the changes necessary for VMEStream to use the bi-directional registers. I'll let you decide if you want to merge these changes or not. Although, I think that this new version is simpler.

**Comment by dabelknap** [comment]
@tsarangi Should I go ahead and close this PR, or do you think it will be used at all?

**Comment by tsarangi** [comment]
@dabelknap 
Sorry, I didn't realize this until now. Why there is a difference in orsc bit file ?

**Comment by dabelknap** [comment]
That bit file was the one Mathias provided that switched the VME registers back to bi-directional. The previous bitfiles has uni-directional registers. I don't know if Mathias has created any new bitfiles since.

**Comment by tsarangi** [comment]
Hi @dabelknap . I have been using the bidirectional registers since quite a while and I think the current bit file has all the requirements you might need. Have you tried ?

**Comment by dabelknap** [comment]
I haven't tried any other bitfiles. I only took the most recent bitfile Mathias had created when I started working on this PR. The most recent bitfiles are still kept in Mathias's area, right?

**Comment by tsarangi** [comment]
No, don't take it from Mathias' area because he might be testing those ...

-Tapas

**Comment by dabelknap** [comment]
It doesn't look like you committed any new bitfiles yourself. The one I have in this PR is probably the one you were using already. It just looks like the repo hasn't been updated with the new file yet, hence the diff.

**Comment by dabelknap** [comment]
VMEStream isn't going to be used, so I am closing this PR.

**Pull request closed without merging**
